### ISSUE TITLE
feature request: enable kernel level load balance (a.k.a SO_REUSEPORT)

### ISSUE THREAD

**Issue by enihcam** [HyNetwork/hysteria#184]
or any balance approaches can distribute traffic via one unique port to multiple hysteria processes.

ref:
https://github.com/v2fly/v2ray-core/commit/39cbe4ab13103d333f78c415b0d0f35904b2d11e

**Comment by tobyxdd** [comment]
Correct me if I'm wrong, but the way I understand how `SO_REUSEPORT` works for UDP is that it evenly distributes packets across all sockets (since there's no concept of a "connection"). If so I don't think it's possible to do load balancing with this, because the state is not shared among multiple hysteria processes.

**Comment by enihcam** [comment]
> 

yes, your understanding is right. i think maybe for the next-gen of hysteria is to make the process stateless by sharing context in a shared heap, so to enable horizontal scale.

**Comment by enihcam** [comment]
`Hysteria server does not have built-in support for multi-port addresses (you cannot use the above format as a listening address)`

@tobyxdd if a process and its state can be separated, `SO_REUSEPORT` can make the support of server-side [multi-port addresses](https://hysteria.network/docs/port-hopping/) possible.

**Comment by haruue** [comment]
`SO_REUSEPORT` cannot bind multiple ports with one socket.

Hysteria server is not supported multi-port addresses by design. Considering a user specified a port range, such as 30000-60000, there are 30000 ports in this range, in other words, we need to open 30000 sockets to listen to all of them if we do not use NAT.
