### ISSUE TITLE
Let's Encrypt Privacy.pem access denied

### ISSUE THREAD

**Issue by glamoroussky** [HyNetwork/hysteria#245]
Hi dear,

I use my own certificate from Let's Encrypt for Hysteria, but it seems like Hysteria cannot access Privkey.pem file.

It says: etc/letsencrypt/.../privkey.pem permission denied.

Is there any way to modify the file's access right for Hysteria to use?

I'm a linux novice, please tell me the command line to execute.

Thanks very much.

**Comment by glamoroussky** [comment]
I tried chmod +x // & chmod 755, they never worked for Hysteria to access privkey.pem.

I only have root user on my server.

**Comment by haruue** [comment]
Did you install the hysteria with our `install_server.sh` script and start it with `systemctl start hysteria-server.service`? It uses a dedicated user to run hysteria.

If so, You can switch to start it with root with the following commands.
```
sed -i '/User=/d' /lib/systemd/system/hysteria-server.service
sed -i '/User=/d' /lib/systemd/system/hysteria-server@.service
systemctl daemon-reload
systemctl restart hysteria-server.service 
# or hysteria-server@xxx.service in case of config files with a customized name
```

Otherwise, please tell us how did you install and start the hysteria on your server.

**Comment by glamoroussky** [comment]
> 

It works!
Thanks so much!
Yes, I used the script to install Hysteria.

Hope the documents can be updated for novices like me.
XD.
